name: CI pipeline #There is the name of our pipeline

#The pipeline expected to run on the branch main when someone do a push 
on :
    push:
        branches: [main]

jobs:
    build: #The name of the job
      runs-on: ubuntu-latest  #This job will run on an ubunto-latest

      steps:
      - name: Checkout_code
        uses : actions/checkout@v5

      - name: Set_up_Node.js
        uses : actions/setup-node@v3
        with:
            node-version: 16

      - name: Install dependancies
        run: npm install

      - name: Run tests
        run: npm test








